### ISSUE TITLE
Is migration ``0024_service_dates_optional.py`` included in the v0.4.3 on PyPi? 

### ISSUE THREAD

**Issue by araichev** [tulsawebdevs/django-multi-gtfs#39]
When i install v0.4.3 via pip, the migration is not included.  Am i doing something wrong or is it actually missing?

**Comment by jwhitlock** [comment]
I've looking in the source tarball and the wheel - the file is in both.  What's the output of `./manage.py migrate` or `./manage.py syncdb`?

**Comment by araichev** [comment]
Hmm, maybe it was a Pip cache problem.  I uninstalled and then reinstalled with ``pip insatll -I multigfts`` and the migration was there.  All good.
