### ISSUE TITLE
django 1.7+ support?

### ISSUE THREAD

**Issue by jheld** [tulsawebdevs/django-multi-gtfs#51]
Hi,

I am interested in using your project in some form, but I want to use a more modern version of django. Can you explain why 1.7 and higher is not supported? If there is interest (like mine) in getting it higher, are you interested in outside help (not just feature requests)?

**Comment by jwhitlock** [comment]
The project is behind on Django versions because I haven't needed this code in a few years. I'd accept a PR that fixes that, including one that limits support to currently supported Django versions and the related Python versions.

**Comment by jwhitlock** [comment]
Released v1.0.0, which includes Django 1.7 - 1.9 support
