### ISSUE TITLE
Handle quotation marks

### ISSUE THREAD

**Issue by jclgoodwin** [tulsawebdevs/django-multi-gtfs#64]
The trips.txt file in this feed https://www.transportforireland.ie/transitData/google_transit_expressbus.zip has some odd lines like 

    46-860-y11-1,"Mo-Fr#1","33.Mo-Fr.46-860-y11-1.2.I","46-860-y11-1.2.I","Aston Quay, stop 4720", "1"

The extra space means `"1"` is used as the `direction_id`, which causes an error (`DataError: value too long for type character varying(1)`).

**Comment by jwhitlock** [comment]
I think the solution is to enable the [skipinitialspace](https://docs.python.org/2/library/csv.html#csv.Dialect.skipinitialspace) behavior of the CSV reader.  In [models/base.py](https://github.com/tulsawebdevs/django-multi-gtfs/blob/master/multigtfs/models/base.py#L21):

    csv_reader = reader(txt_file, skipinitialspace=True)

With this change, I can import that feed.

**Comment by jwhitlock** [comment]
Fixed by #68
