### ISSUE TITLE
"String or unicode input unrecognized as WKT EWKT, and HEXEWKB"

### ISSUE THREAD

**Issue by jclgoodwin** [tulsawebdevs/django-multi-gtfs#70]
`stops.txt` in https://si.metzmetropole.fr/fiches/opendata/gtfs_current.zip has some lines like this:

    10258,TANEU,TANNEURS,,+49.119799,+06.182966,1,

The + sign prevents PostGIS from recognising `POINT(+06.182966 +49.119799)` as valid input.

**Comment by jwhitlock** [comment]
Thanks for the bug report. I think this should be a straightforward fix.

**Comment by jwhitlock** [comment]
With #71 merged, this feed now imports cleanly.

<img width="736" alt="le met" src="https://user-images.githubusercontent.com/286017/29737334-4cf26cb0-89d1-11e7-912c-23b7004a4e21.png">
