### ISSUE TITLE
Django 2.0.* support

### ISSUE THREAD

**Issue by sinia** [tulsawebdevs/django-multi-gtfs#85]
It seems that django-multi-gtfs does not properly support Django v2.0. After installing and adding "multigtfs" to Django project settings.py I am getting the error below when running manage.py. 

`  File "/home/ainis/.local/share/virtualenvs/django-PDLdwLSU/lib/python3.6/site-packages/multigtfs/models/base.py", line 24, in <module>
    from django.contrib.gis.db.models.query import GeoQuerySet
ModuleNotFoundError: No module named 'django.contrib.gis.db.models.query'
`

When running on Django 1.11 there is no such problem. It seems that this is caused by the fact that GeoQuerySet was removed Django 2:
https://docs.djangoproject.com/en/2.1/releases/2.0/
> The GeoManager and GeoQuerySet classes are removed.

**Comment by jclgoodwin** [comment]
[This has been fixed](https://github.com/tulsawebdevs/django-multi-gtfs/commit/7d306965d9710bb4124d18538ab503798a41bcd3) but not yet released to pypi just yet

**Comment by jwhitlock** [comment]
Thanks for checking @jclgoodwin. I’ll release a new version this weekend, and see if I can squeeze in Django 2.1 support.

**Comment by jwhitlock** [comment]
Version 1.1.2 released. Django 2.1 required no changes, so that works as well.
